# Site settings
title: "Anthony Reboul"
email: "anthony.reboul@gmail.com"
description: Android Developer> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: @anthony_reboul
github_username: anthony-reboul

# Build settings
markdown: kramdown
